global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "db_app"
    static_configs:
      - targets: ["db_app:8000"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]
